<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LeaveApproval.IService\LeaveApproval.IService.csproj" />
    <ProjectReference Include="..\LeaveApproval.IStore\LeaveApproval.IStore.csproj" />
    <ProjectReference Include="..\LeaveApproval.StoreContainer\LeaveApproval.StoreContainer.csproj" />
  </ItemGroup>

</Project>
